
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include templates.yaml

# settings for InfluxDB
influxdb:
  host: 192.168.0.110
  port: 8086
  database: homeassistant
  username: !secret influx_user
  password: !secret influx_pw
  ssl: false
  verify_ssl: false
  max_retries: 3
  tags:
    source: HA
  tags_attributes:
    - friendly_name
  default_measurement: state
  